// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStreamKey(arg1) {
  return window['go']['main']['App']['GetStreamKey'](arg1);
}

export function StartBackend() {
  return window['go']['main']['App']['StartBackend']();
}

export function StopBackend() {
  return window['go']['main']['App']['StopBackend']();
}

export function ToggleFRPC() {
  return window['go']['main']['App']['ToggleFRPC']();
}

export function UpdateHtmlTitle(arg1) {
  return window['go']['main']['App']['UpdateHtmlTitle'](arg1);
}
