// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetStreamKey(arg1:context.Context):Promise<void>;

export function StartBackend():Promise<void>;

export function StopBackend():Promise<void>;

export function ToggleFRPC():Promise<void>;

export function UpdateHtmlTitle(arg1:string):Promise<void>;
